### ISSUE TITLE
Add vcard:post-office-box to Address

### ISSUE THREAD

**Issue by tomlind** [MetaSolutionsAB/dcat-manager#32]
To enter a valid postal address it is often necessary to record a post office box, and not a street address, For example: SGU, Box 670, 75128 Uppsala, Sweden

Should be optional with maximum 1 entry

**Comment by matthiaspalmer** [comment]
The RDF vocabulary shows that vcard:post-office-box is deprecated:
http://www.w3.org/TR/vcard-rdf/#d4e1110

And the RFC 6350, upon which the RDF vocabulary rests states:
(http://tools.ietf.org/html/rfc6350#section-6.3.1)

    Experience with vCard 3 has shown that the first two components
    (post office box and extended address) are plagued with many
    interoperability issues.  To ensure maximal interoperability,
    their values SHOULD be empty.

Hence, it doesn't seem to be a good idea to add it.

**Comment by tomlind** [comment]
So, in oppnadata.se we put post office box number in the street name property? Or we don't use our postal address at all?

**Comment by ebner** [comment]
oppnadata.se will probably not show any information related to postal addresses and the DCAT(-AP) specifications are not really clear on how to handle them (except for recommending to use vCard).

We recommend to use the normal address field for providing PO Box information as there currently does not seem to be another option to express such information.
