### ISSUE TITLE
I can´t save our "Riktlinjer för återanvändning".

### ISSUE THREAD

**Issue by thomaskvist** [MetaSolutionsAB/dcat-manager#50]
I can´t save our "Riktlinjer för återanvändning". It seems that the text is too long? No error message though. And I really need a bigger textfield if that is the problem

**Comment by matthiaspalmer** [comment]
Could you send me the text so I can test?

**Comment by thomaskvist** [comment]
Here is the text: All data is published without any guarantees regarding quality or actuality. The publishing of data can be discontinued or delayed without forewarning. All kinds of usage of the data is strictly the sole responsibility of the re-user.

**Comment by matthiaspalmer** [comment]
Ah, according to the specification (ODRS) this field is supposed to be a reference to a document, that is a URL. I have now indicated this more clearly (in several places) by changing the help text (click on the label) and also marking the field in red if it is not a correct URL.
