### ISSUE TITLE
Eurovoc link correct?

### ISSUE THREAD

**Issue by thomaskvist** [MetaSolutionsAB/dcat-manager#52]
When using "Tema/Kategori" an uri/url to eurovoc is created. But the link created does not point to any HTML or RDF-page as far as I can see. Should you not get to a page describing e.g. the theme "economy"?

**Comment by ebner** [comment]
The URIs are correct, we are using the official EuroVoc SKOS file. It seems as if LD principles are not completely followed, not much we can do about this.
