### ISSUE TITLE
Language code

### ISSUE THREAD

**Issue by thomaskvist** [MetaSolutionsAB/dcat-manager#54]
Shouldn´t the langauage code be mandatory if it is possible to assigning a field a language code?

I would also like to have language codes for nyckelord, ansvarig utgivare. 

Finallly, I would like to have the possibility to enter e.g titles both in swedish and english instead of having to choose only one language.

**Comment by matthiaspalmer** [comment]
1) According to the DCAT-AP specification the language code on the catalog level is optional.
In principle the languages of the catalog can be detected automatically by checking all language tags of the metadata expressions of every dataset and distribution. We do not have any such automatic procedure though, and neither is one required from the specification. Hence, we are stuck with an optional language code on the catalog level.

2) Language codes for "nyckelord" or "keyword" in english is certainly a good idea, I have changed this now, must have been an oversight from my part, sorry. Language code for "ansvarig utgivare" ("publisher" in english) is also possible as foaf:name seems to support this. It is fixed.

3) Choosing multiple languages for a single value is not supported in RDF natively, although we could make a trick in the user interface to allow editing of multiple values at the same time. However, this requires quite some work in an underlying library (RDForms) and cannot be fixed as quickly. I will have it in mind for the future.
