### ISSUE TITLE
Fel länk till geonames?

### ISSUE THREAD

**Issue by thomaskvist** [MetaSolutionsAB/dcat-manager#56]
Det verkar som att fel länk från geonames används. Om man anger 
lhttp://www.geonames.org/3020251/about.rdf för men en URI/URL so innehåller data och dessutom finns en HTML-variant om man anger suffixet html. I DCATAP-filen borde väl -aboutfilerna användas? Då kan man ju hämta namn på det geografiska objekten därifrån när man använder DCAT AP-filen

**Comment by matthiaspalmer** [comment]
Det är viktigt att använda den URI som används i RDF filerna annars blir grafen inte ihopkopplad.

Dvs om vi skulle länka till "http://www.geonames.org/3020251/about.rdf" och får RDF tillbaka där metadatan talar om URIn "http://sws.geonames.org/3020251/" så kopplas inte grafen ihop.
Dvs, om vi länkar till about.rdf så refererar vi inte till en geografisk position utan till en text fil som innehåller RDF.

Vi gör alltså rätt idag som refererar till URIn "http://sws.geonames.org/3020251/" då det är den officiella identifieraren för en geografisk position som geonames definierat.

**Comment by thomaskvist** [comment]
Vi vill ju använda URI:n som utgångspunkt för en url – helt enkelt genom att lägga till .rdf till URI:n och i denna fil hämta label och annat som behövs när vi ska skapa en mänskligt läsbar variant av DCAT-AP-filen. Jag har förstått att det är så det egentligen bör fungera.

Men det verkar som vi får lägga till /about.rdf på egen hand just för geonames för att åstadkomma detta. Alltid lite olyckligt med specialvarianter dock.

Hälsningar
Thomas

Thomas Kvist
Projektledare IT

+46(0)90-161198
+46(0)70-3497631 (mobil)
thomas.kvist1 (Skype)
thomas.kvist@umea.se<mailto:thomas.kvist@umea.se>
Umeå kommun
IT-funktionen
901 84 Umeå

Besöksadress: Skolgatan 31A
www.umea.se/kommun
[Logotyp, Umeå kommun]

Från: matthiaspalmer [mailto:notifications@github.com]
Skickat: den 11 september 2015 11:11
Till: MetaSolutionsAB/dcat-manager
Kopia: Thomas Kvist
Ämne: Re: [dcat-manager] Fel länk till geonames? (#56)


Det är viktigt att använda den URI som används i RDF filerna annars blir grafen inte ihopkopplad.

Dvs om vi skulle länka till "http://www.geonames.org/3020251/about.rdf" och får RDF tillbaka där metadatan talar om URIn "http://sws.geonames.org/3020251/" så kopplas inte grafen ihop.
Dvs, om vi länkar till about.rdf så refererar vi inte till en geografisk position utan till en text fil som innehåller RDF.

Vi gör alltså rätt idag som refererar till URIn "http://sws.geonames.org/3020251/" då det är den officiella identifieraren för en geografisk position som geonames definierat.

**Comment by matthiaspalmer** [comment]
Om behovet är att få ut RDF så går det aldeles utmärkt genom att göra följande request: 
GET http://sws.geonames.org/3020251/
accept: application/rdf+xml

Dvs, man ska använda sig av content-negotiation för att be om RDF i requestet, om man inte anger någon accept får man en redirect till en html-sida. Antar att det är det som du upplevt.

**Comment by thomaskvist** [comment]
Perfekt!
Tack för infon!

Hälsningar
Thomas



Skickat från min Samsung-enhet


-------- Originalmeddelande --------
Från: matthiaspalmer <notifications@github.com>
Datum: 2015-09-11 11:44 (GMT+01:00)
Till: MetaSolutionsAB/dcat-manager <dcat-manager@noreply.github.com>
Kopia: Thomas Kvist <thomas.kvist@umea.se>
Rubrik: Re: [dcat-manager] Fel länk till geonames? (#56)


Om behovet är att få ut RDF så går det aldeles utmärkt genom att göra följande request:
GET http://sws.geonames.org/3020251/
accept: application/rdf+xml

Dvs, man ska använda sig av content-negotiation för att be om RDF i requestet, om man inte anger någon accept får man en redirect till en html-sida. Antar att det är det som du upplevt.
