### ISSUE TITLE
Språktagg "em"? Borde väl vara "en"?

### ISSUE THREAD

**Issue by thomaskvist** [MetaSolutionsAB/dcat-manager#57]
Vi har fått feedback från de som använder vår fil att språktaggen "em" finns här och där. Gissar att det ska vara en felstavning någonstans.

**Comment by matthiaspalmer** [comment]
Ah, bra fångat. Det var ett stavfel i koden.
Korrigerat och uppdaterat på dcat-editor.com.

För gammal data ska det räcka att bara ta bort och sen lägga till spatial informationen så ska det bli rätt.
